import { ApiError } from '../../errors/ApiError.js'
import { createSinglePlace } from '../../usecases/placeUsecases/createSinglePlace.js'

const savePlace = async (req, res, next) => {
  try {
    const newPlace = req.body

    // const { id } = req.user

    //Validate payload equals to the user in the database they need to match.
    //Otherwise throw an error.

    // const foundUser = await getSingleUser({ _id: id })

    const savedPlace = await createSinglePlace(newPlace)

    if (savedPlace) {
      res.json({
        message: 'success',
        statusCode: 200,
        description: 'Place created successfully',
        data: savedPlace,
      })
    }
  } catch (err) {
    if (err.name === 'ValidationError') {
      next(
        ApiError.badRequest({
          message: 'Validation Error',
          errors: err,
        })
      )
      return
    } else {
      console.log(err)
      next({})
    }
  }
}

export { savePlace }
